### PR TITLE
Support installing default pip packages

### PR DESCRIPTION
**Pull request by rlex**
Subj. Allows you to install default packages on each python install.
Basically same as in nodejs / ruby official plugins: 
https://github.com/asdf-vm/asdf-nodejs/blob/master/bin/install#L238-L252 
https://github.com/asdf-vm/asdf-ruby/blob/master/bin/install#L52-L71

pkgs should be listed in ~/.default-eggs, one per line.
I'm not sure if "egg" is correct naming for python pkgs, though.

### CODE REVIEW

**Comment by rlex** [comment]
any updates on this?

**Comment by tuvistavie** [comment]
Hi, sorry for the delay and thank you for the PR.
I think this feature is a good idea, but I do not like the name of the file, as egg is a packaging format which is being replaced by wheel. As this is a way to install Python packages, I would rather simply name the file `~/.default-python-packages`. What do you think.

**Comment by rlex** [comment]
Yep, looks better.
Should be good now?

**Comment by danhper** [comment]
Great, thank you!

**Comment by adamyonk** [comment]
Should update the readme with this!

**Pull request merged**
